apiVersion: v1
kind: Service
metadata:
  name: pack-optimizer
  labels:
    app: pack-optimizer
spec:
  type: {{ .Values.service.type }}
  selector:
    app: pack-optimizer
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
