// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pack

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PackSize struct {
	ID        int32
	Size      int16
	CreatedAt pgtype.Timestamptz
}
