// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pack_sizes.sql

package pack

import (
	"context"
)

const deletePackSizes = `-- name: DeletePackSizes :exec
DELETE FROM pack_sizes
`

func (q *Queries) DeletePackSizes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deletePackSizes)
	return err
}

const insertPackSizes = `-- name: InsertPackSizes :exec
INSERT INTO pack_sizes (size)
SELECT unnest($1::smallint[])
`

func (q *Queries) InsertPackSizes(ctx context.Context, sizes []int16) error {
	_, err := q.db.Exec(ctx, insertPackSizes, sizes)
	return err
}

const listPackSizes = `-- name: ListPackSizes :many
SELECT size FROM pack_sizes ORDER BY size
`

func (q *Queries) ListPackSizes(ctx context.Context) ([]int16, error) {
	rows, err := q.db.Query(ctx, listPackSizes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int16
	for rows.Next() {
		var size int16
		if err := rows.Scan(&size); err != nil {
			return nil, err
		}
		items = append(items, size)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
