// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pack

import (
	"context"
)

type Querier interface {
	DeletePackSizes(ctx context.Context) error
	InsertPackSizes(ctx context.Context, sizes []int16) error
	ListPackSizes(ctx context.Context) ([]int16, error)
}

var _ Querier = (*Queries)(nil)
